### ISSUE TITLE
MAI-1 Centralization Risk Due to High Trust Assumptions Required

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#410] opened 2024-08-21 17:54 UTC
MAI-1 Centralization Risk Due to High Trust Assumptions Required
Auditor: Movebit
Code: Aptos Core
Severity: Informational
Discovery Methods: Manual Review
Status: Pending

Code Location:
networks/suzuka/suzuka-full-node/src/main.rs#8

Descriptions:
The current architecture introduces a centralization risk as it requires higher trust
assumptions. Light nodes and Celestia nodes are pivotal to the network’s security, and any malicious behavior from these nodes could have severe consequences. This level of centralization necessitates more robust trust assumptions than is ideal, potentially impacting the overall security and reliability of the network.

Suggestion:
Reevaluate the trust model to minimize centralization and reduce reliance on light nodes and
Celestia nodes. Consider architectural adjustments to distribute trust more evenly and enhance the overall security of the network.

**Comment by l-monninger** [comment] 2024-08-22 08:07
I need more information from them here. Celestia namespaces are permissionless. As is being discussed in governance, we actually ought to make this more restrictive and only accept signed blobs from accounts which are staked in MCR. 

If they are referring to the need to run a light node, the connection between a rollup and light node is always trusted. This why architecturally, these are both run within a trusted perimeter. It is the job of the light node itself to reduce the trust assumptions w.r.t. the Celestia network as a whole.

**Comment by jlguochn** [comment] 2024-08-23 02:12
Thank you for the response. I would like to provide further context.
In the implementation, blobs read by the light node from the DA are treated as successfully verified by default. Additionally, in the read_blocks_from_da function, full nodes read blocks from light nodes and can execute them without thorough verification. Moreover, the RPC provided by the light node lacks permission checks. Furthermore, the light node's Verifier trait is also not fully implemented. In a single light node environment, if the light node stops functioning, it can cause the full node to crash and exit.

This implementation relies on several trust assumptions:
1. Blobs read from the DA do not require further verification.
2. The light node will not perform malicious actions, such as DOS attacks, against the full node.
3. The light node operates in a trusted environment where its RPC is not susceptible to malicious third-party calls.

Given these aspects, the current implementation necessitates higher trust assumptions, Our assessment is based on the implementation in the commit we audited. and we understand they may be addressed in future implementations and optimizations, Therefore, the issue is flagged as "Informational" to highlight potential areas for improvement.

**Comment by l-monninger** [comment] 2024-09-10 08:58
> The light node operates in a trusted environment where its RPC is not susceptible to malicious third-party calls.

This is the core assumption. Closing this.

**Closed by l-monninger** 2024-09-10 08:58 UTC
Labels: Source: Audit, suzuka:decentralization
