### ISSUE TITLE
(HAL-25) SEQUENCE NUMBER MISMATCH IN TRANSACTION PROCESSING

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#594] opened 2024-09-12 19:31 UTC
(HAL-25) SEQUENCE NUMBER MISMATCH IN TRANSACTION PROCESSING
Auditor: Halborn
Severity: Informational 

Description
In the opt-executor transaction processing implementation in tick_transaction_pipe, there is a discrepancy between the sequence number used for transaction validation and the one used for adding the transaction to the mempool.

![Screenshot 2024-09-12 at 12 31 10 PM](https://github.com/user-attachments/assets/7c18d128-cfe9-4c01-b0f3-959a87cfcf8e)

This mismatch bypasses an essential verification ensuring that user cannot use sequences that they already used. Fortunately, the execution VM performs the same verification upstream, but that could have an impact on future upgrades.

Score
[AO:A/AC:L/AX:L/R:N/S:U/C:N/A:N/I:N/D:N/Y:N (0.0)](https://www.halborn.com/bvss?q=AO%3AA%2FAC%3AL%2FAX%3AL%2FR%3AN%2FS%3AU%2FC%3AN%2FA%3AN%2FI%3AN%2FD%3AN%2FY%3AN)
![Screenshot 2024-09-12 at 12 31 43 PM](https://github.com/user-attachments/assets/6e7cb7f6-2476-4d45-8022-6b2f3b62a6f9)

Recommendation
It is recommended to use the sequence number from the database instead of the one from the transaction.

**Comment by mzabaluev** [comment] 2024-09-17 11:46
Duplicate of #415

**Closed by mzabaluev** 2024-09-17 11:46 UTC
Labels: Source: Audit

**Comment by l-monninger** [comment] 2024-10-24 09:54
This has been dealt with or modified in several forms. The latest change to sequence number validation to prevent GAS DOS was included in #722.
