### ISSUE TITLE
MST-5 slash Issue

### ISSUE THREAD

**Issue by SA124** [movementlabsxyz/movement#527] opened 2024-09-05 15:56 UTC
MST-5 slash Issue

Auditor: Movebit
Code: MCR Settlement Contract
Severity: Discussion
Status: Pending

Code Location:
protocol-units/settlement/mcr/contracts/src/staking/MovementStaking.sol

Descriptions:
The slash mechanism makes the nodes accountable for their actions and can deter
malicious attack behavior and negligence, ensuring a robust and trustworthy network infrastructure. But the slash function in the contract can only manipulate data from msg.sender , meaning it can only be called by the user who is being slashed himself, and all
the parameters are controllable, it's needed to make sure that this is by design.

Suggestion:
It is recommended to ensure that this is as designed.

**Comment by mzabaluev** [comment] 2024-09-09 09:24
Duplicate of #451.

**Closed by mzabaluev** 2024-09-09 09:24 UTC
Labels: duplicate, suzuka:settlement, Source: Audit
